debuging ENV_nAME

diff --git a/.github/workflows/synchronize.yml b/.github/workflows/synchronize.yml
--- a/.github/workflows/synchronize.yml
+++ b/.github/workflows/synchronize.yml
@@ -1,90 +1,100 @@
-# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
-#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
-#    and best practices on handling the access key credentials.
-
-name: Synchronize Deployment
-
+name: Appealio-API Workflow
 on:
+  push:
+    branches:
+      - master
+      - staging
+      - showcase
+      - dev
+      - uat
   pull_request:
     types:
-      - synchronize
       - labeled
-  label: {cerritos, voyager, enterprise}
+
+env:
+  ENV_NAME: 'dirty'
 
 jobs:
-  checkLabels:
+  runDeployment:
+    name: Run Deployment
     runs-on: ubuntu-22.04
-    if: ${{ github.event.label.name == 'cerritos' }} ||
-      ${{ github.event.label.name == 'enterprise' }} ||
-      ${{ github.event.label.name == 'voyager' }}
-    steps:
-      - name: Labels
-        env:
-          LABEL: ${{ github.event.label.name }}
-        run: |
-          echo LABELS should match test envs names
 
-  deploy:
-    needs: [checkLabels]
-    name: Deployment for test Environments
-    runs-on: ubuntu-22.04
-    env:
-      CI: false
-    container:
-      image: leapfrogtechnology/envault:0.4.6-node10.16.0-stretch-slim
     steps:
       - name: Checkout
         uses: actions/checkout@v3
 
+      # Stage Setup
       - name: Setup Stage
         shell: bash
-        env:
-          CI: false
-          LABEL: ${{ github.event.label.name }}
         run: |
-          echo "export STAGE=${{ LABEL }}" >> ~/.bash_profile
+          sudo apt -y update || true
+          if [ $GITHUB_REF_NAME == "master" ]
+          then
+            echo "export STAGE=prod" >> ~/.bash_profile
+          elif [ $GITHUB_REF_NAME == "staging" ]
+          then
+            echo "export STAGE=staging" >> ~/.bash_profile
+          elif [ $GITHUB_REF_NAME == "showcase" ]
+          then
+            echo "export STAGE=showcase" >> ~/.bash_profile
+          elif [ $GITHUB_REF_NAME == "dev" ]
+          then
+            echo "export STAGE=dev" >> ~/.bash_profile
+          elif [ $GITHUB_REF_NAME == "uat" ]
+          then
+            echo "export STAGE=uat" >> ~/.bash_profile
+          elif [ ${{ github.event.label.name }} == 'enterprise' ]
+          then
+            echo "export STAGE=enterprise" >> ~/.bash_profile
+          elif [ ${{ github.event.label.name }} == 'voyager' ]
+          then
+            echo "export STAGE=voyager" >> ~/.bash_profile
+          elif [ ${{ github.event.label.name }} == 'cerritos' ]
+          then
+            echo "export STAGE=cerritos" >> ~/.bash_profile
+          else
+            echo "export STAGE=dirty" >> ~/.bash_profile
+          fi
+          source ~/.bash_profile
+          echo "::set-env name=ENV_NAME::$STAGE"
+          echo $ENV_NAME
 
-      - name: Login to AWS
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+#      # Login
+#      - name: Login to AWS
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          aws-region: ${{ secrets.AWS_REGION }}
+#        if: contains(fromJson('["prod", "staging", "showcase", "enterprise", "voyager", "cerritos"]'), ENV_NAME)
 
-      - name: Run Deployment
+      # Deploy Services
+      - name: Deploy Services to AWS
         shell: bash
         run: |
-          source ~/.bash_profile
-          echo $STAGE
+          echo $ENV_NAME
+#          source ~/.bash_profile
+#          chmod +x deploy/deploy.sh
+#          deploy/deploy.sh $STAGE
+        if: contains(fromJson('["prod", "staging", "showcase", "enterprise", "voyager", "cerritos"]'), $ENV_NAME)
 
-#  notify:
-#    needs: [deploy]
-#    name: Notify on Slack
-#    runs-on: ubuntu-22.04
-#    steps:
+#      # send notifications to slack channel
 #      - name: Notify Slack Success
 #        if: success()
+#        uses: rtCamp/action-slack-notify@v2.2.0
 #        env:
-#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
-#        uses: voxmedia/github-action-slack-notify-build@v1.5.0
-#        with:
-#          message_id: ${{ steps.slack.outputs.message_id }}
-#          channel: monitoring
-#          status: SUCCESS
-#          color: good
+#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+#          SLACK_MESSAGE: 'Build Succeed :rocket:'
+#          SLACK_USERNAME: 'GitHub_Actions'
+#          SLACK_ICON: https://docvocate.com/assets/img/logo.png
+#          SLACK_COLOR: 'good'
 #
 #      - name: Notify Slack Fail
 #        if: failure()
+#        uses: rtCamp/action-slack-notify@v2.2.0
 #        env:
-#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
-#        uses: voxmedia/github-action-slack-notify-build@v1.5.0
-#        with:
-#          message_id: ${{ steps.slack.outputs.message_id }}
-#          channel: monitoring
-#          status: FAILED
-#          color: danger
-
-
-
-
-
+#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+#          SLACK_MESSAGE: 'Build Failed :x:'
+#          SLACK_USERNAME: 'GitHub_Actions'
+#          SLACK_ICON: https://docvocate.com/assets/img/logo.png
+#          SLACK_COLOR: '#F32013'
